# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94d885860c5c716df26d5bd0cb8029beb9fb3bc73a17336e0e6f78c2a21da577e1f26501b228d5844b1e9d893a407eeded02792dfe14a113274a085801169350

test:
  secret_key_base: fc0b01a0bf21256efe5eb12a9e799e1cf17609a9e980f4fc9a8d274418fbde30dfcf588064629878f8aa2dcb9a6823d2769bced32c1de2a25244095a49116484

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
